RVPYTH Continuous Delivery & Continuous Integration
Social-projects-Rivne/Rv-025.Python pull request #18
Opened 2017-07-18 12:18 UTC by yurapa

Used services: [Travis](https://travis-ci.org/) and [Heroku](https://heroku.com).

TODO: please rename file "restaurant/local_settings.example" to "restaurant/local_settings.py".

As result we have:
restaurant/settings.py -> settings for production
restaurant/local_settings.py -> settings for local running server (ignored on repository).

Link to our project: [restaurant-rv.herokuapp.com](https://restaurant-rv.herokuapp.com/admin/)

2017-07-18 14:11 UTC, krizik approved these changes

2017-07-18 15:34 UTC, ivanna-ostrovets requested changes

2017-07-18 15:34 UTC, ivanna-ostrovets commented on .gitignore
> +# for Herocu
Please, fix typo in "Herocu" (it should be "Heroku").

2017-07-18 19:56 UTC, krizik approved these changes

2017-07-18 19:58 UTC, krizik approved these changes

2017-07-19 08:42 UTC, OlhaLesk approved these changes

2017-07-19 08:54 UTC, ivanna-ostrovets approved these changes

2017-07-19 08:54 UTC, merged