Update Travis config
Social-projects-Rivne/Rv-025.Python pull request #28
Opened 2017-07-24 20:52 UTC by ivanna-ostrovets

[RVPYTH-79 Continuous Delivery & Continuous Integration](http://ssu-jira.softserveinc.com/browse/RVPYTH-79)

2017-07-25 06:02 UTC, yurapa approved these changes

2017-07-25 08:15 UTC, serge30 requested changes

2017-07-25 08:15 UTC, serge30 commented on restaurant/settings.py
> +    DATABASES['default'] = {'ENGINE': 'django.db.backends.postgresql'}
It's bad idea to check command line arguments from underlying modules as tests could be run in differ way than `./manage.py test`. I'd rather just remove this check and set default DB in all cases.

2017-07-25 08:15 UTC, serge30 commented on .travis.yml
> +    - script: pip install flake8 --quiet && flake8 .
Please move `flake8` installation to `install` section. It is not an issue to have extra modules installed during tests run.

2017-07-26 07:22 UTC, serge30 approved these changes

2017-07-26 10:36 UTC, krizik approved these changes

2017-07-26 10:37 UTC, OlhaLesk approved these changes

2017-07-26 10:39 UTC, merged