Rvpyth 55 user model
Social-projects-Rivne/Rv-025.Python pull request #5
Opened 2017-07-12 08:54 UTC by OlhaLesk

RVPYTH-55
To write user model

2017-07-12 10:04 UTC, yurapa approved these changes

2017-07-12 15:24 UTC, krizik approved these changes

2017-07-13 22:19 UTC, ivanna-ostrovets requested changes

2017-07-13 22:19 UTC, ivanna-ostrovets commented on administrator/models/user_profile.py
> +"""
Please, refactor this according to PEP 257.

> Any indentation in the first line of the docstring (i.e., up to the first newline) is insignificant and removed.
[https://www.python.org/dev/peps/pep-0257/#handling-docstring-indentation](url)

2017-07-13 22:19 UTC, ivanna-ostrovets commented on administrator/models/user_profile.py
> +    models.user_profile
Can you explain what does it means?

2017-07-13 22:19 UTC, ivanna-ostrovets commented on administrator/models/user_profile.py
> +    This module contains model class for users.
Please, refactor this according to PEP 257.
> The entire docstring is indented the same as the quotes at its first line
[https://www.python.org/dev/peps/pep-0257/#multi-line-docstrings](url)

2017-07-13 22:19 UTC, ivanna-ostrovets commented on administrator/models/user_profile.py
> +class UserManager(BaseUserManager):
Please, refactor this according to PEP 8.

> Surround top-level function and class definitions with two blank lines.
[https://www.python.org/dev/peps/pep-0008/#blank-lines](url)

2017-07-13 22:19 UTC, ivanna-ostrovets commented on administrator/models/user_profile.py
> +
Please, refactor this according to PEP 8.

> Surround top-level function and class definitions with two blank lines.
[https://www.python.org/dev/peps/pep-0008/#blank-lines](url)

2017-07-13 22:19 UTC, ivanna-ostrovets commented on administrator/models/user_profile.py
> +class UserManager(BaseUserManager):
Class docstring is missing. Please, add it.

2017-07-13 22:19 UTC, ivanna-ostrovets commented on administrator/models/user_profile.py
> +        """Creates and saves a User with the given email, name and password."""
Please, refactor this according to PEP 257.
> The docstring is a phrase ending in a period. It prescribes the function or method's effect as a command ("Do this", "Return that"), not as a description; e.g. don't write "Returns the pathname ...".
[https://www.python.org/dev/peps/pep-0257/#one-line-docstrings](url)

2017-07-13 22:19 UTC, ivanna-ostrovets commented on administrator/models/user_profile.py
> +    def create_user(self, email, name, password, **extra_fields):
Function docstring is missing. Please, add it.

2017-07-13 22:19 UTC, ivanna-ostrovets commented on administrator/models/user_profile.py
> +        """Creates and saves a superuser with the given email, name and password."""
Please, refactor this according to PEP 257.
> The docstring is a phrase ending in a period. It prescribes the function or method's effect as a command ("Do this", "Return that"), not as a description; e.g. don't write "Returns the pathname ...".
[https://www.python.org/dev/peps/pep-0257/#one-line-docstrings](url)

2017-07-13 22:19 UTC, ivanna-ostrovets commented on administrator/models/user_profile.py
> +        A class implementing a fully featured User model with admin-compliant
Please, refactor this according to PEP 257.
> The entire docstring is indented the same as the quotes at its first line
[https://www.python.org/dev/peps/pep-0257/#multi-line-docstrings](url)

2017-07-13 22:19 UTC, ivanna-ostrovets commented on administrator/models/user_profile.py
> +        """Returns the name of the user"""
Please, refactor this according to PEP 257.
> The docstring is a phrase ending in a period. It prescribes the function or method's effect as a command ("Do this", "Return that"), not as a description; e.g. don't write "Returns the pathname ...".
[https://www.python.org/dev/peps/pep-0257/#one-line-docstrings](url)

2017-07-13 22:19 UTC, ivanna-ostrovets commented on administrator/models/user_profile.py
> +        """Sends an email to the user"""
Please, refactor this according to PEP 257.
> The docstring is a phrase ending in a period. It prescribes the function or method's effect as a command ("Do this", "Return that"), not as a description; e.g. don't write "Returns the pathname ...".
[https://www.python.org/dev/peps/pep-0257/#one-line-docstrings](url)

2017-07-13 22:19 UTC, ivanna-ostrovets commented on requirements.txt
> +Pillow==4.2.1
Can you explain why Pillow is needed?

2017-07-13 22:19 UTC, ivanna-ostrovets commented on administrator/models/user_profile.py
> +    """This class is used to handle data about users in DB.
Please, refactor this according to PEP 257.

>The docstring is a phrase ending in a period. It prescribes the function or method's effect as a command ("Do this", "Return that"), not as a description; e.g. don't write "Returns the pathname ...".
https://www.python.org/dev/peps/pep-0257/#one-line-docstrings

Example from Django
>  """Collect Fields declared on the base classes."""

2017-07-13 22:19 UTC, ivanna-ostrovets commented on administrator/models/user_profile.py
> +        """This class gives some options (metadata) attached to the model."""
Please, refactor this according to PEP 257.

>The docstring is a phrase ending in a period. It prescribes the function or method's effect as a command ("Do this", "Return that"), not as a description; e.g. don't write "Returns the pathname ...".
https://www.python.org/dev/peps/pep-0257/#one-line-docstrings

Example from Django
>  """Collect Fields declared on the base classes."""

2017-07-13 22:19 UTC, ivanna-ostrovets commented on administrator/models/user_profile.py
> +    This module contains model class for users.
Please, refactor this according to PEP 257.
> The docstring is a phrase ending in a period. It prescribes the function or method's effect as a command ("Do this", "Return that"), not as a description; e.g. don't write "Returns the pathname ...".
[https://www.python.org/dev/peps/pep-0257/#one-line-docstrings](url)

2017-07-13 22:19 UTC, ivanna-ostrovets commented on restaurant/settings.py
> +#User's model
Please, refactor this according to PEP 8.

> Each line of a block comment starts with a # and a single space (unless it is indented text inside the comment)[https://www.python.org/dev/peps/pep-0008/#block-comments](url)

2017-07-13 22:19 UTC, ivanna-ostrovets commented on restaurant/settings.py
> +#Files downloaded by the users of the site
Please, refactor this according to PEP 8.

> Each line of a block comment starts with a # and a single space (unless it is indented text inside the comment)[https://www.python.org/dev/peps/pep-0008/#block-comments](url)

2017-07-13 22:19 UTC, ivanna-ostrovets commented on administrator/models/__init__.py
> +from .user_profile import UserManager
Maybe it's better to add a new line at the end of the file? This will prevent the line from being displayed as modified in future.

2017-07-13 22:19 UTC, ivanna-ostrovets commented on administrator/models/user_profile.py
> +        send_mail(subject, message, sender, [self.email], **kwargs)
Maybe it's better to add a new line at the end of the file? This will prevent the line from being displayed as modified in future.

2017-07-13 22:19 UTC, ivanna-ostrovets commented on restaurant/settings.py
> +MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
Maybe it's better to add a new line at the end of the file? This will prevent the line from being displayed as modified in future.

2017-07-13 22:19 UTC, ivanna-ostrovets commented on administrator/models/user_profile.py
> +                                  'unique': _("A user with such email already exists."), })
Please, refactor this according to PEP 8.
> Limit all lines to a maximum of 79 characters.
[https://www.python.org/dev/peps/pep-0008/#maximum-line-length](url)

2017-07-13 22:19 UTC, ivanna-ostrovets commented on administrator/models/user_profile.py
> +        """Creates and saves a superuser with the given email, name and password."""
Please, refactor this according to PEP 8.
> The Python standard library is conservative and requires limiting lines to 79 characters (and docstrings/comments to 72).
[https://www.python.org/dev/peps/pep-0008/#maximum-line-length](url)

2017-07-14 15:03 UTC, OlhaLesk commented on requirements.txt
> +Pillow==4.2.1
You should install Pillow because it allows uploading of images of through the admin page.

2017-07-14 21:57 UTC, ivanna-ostrovets requested changes

2017-07-14 21:57 UTC, ivanna-ostrovets commented on administrator/models/user_profile.py
> +:copyright: (c) 2017 by Ol'ha Leskovs'ka
Probably you shouldn't leave your copyright here, because it's our team project.

2017-07-14 21:57 UTC, ivanna-ostrovets commented on configurations/config.ini.example
> +UNAUTHORIZED = 3
New line at the end of the file is missing. Please, add it.

2017-07-15 11:48 UTC, ivanna-ostrovets approved these changes

2017-07-15 12:14 UTC, merged