Rvpyth 59 customize login
Social-projects-Rivne/Rv-025.Python pull request #6
Opened 2017-07-12 11:32 UTC by pika1989

RVPYTH-59
To customize login page

2017-07-12 14:17 UTC, OlhaLesk approved these changes

2017-07-12 14:21 UTC, krizik approved these changes

2017-07-13 19:24 UTC, ivanna-ostrovets approved these changes

2017-07-13 22:31 UTC, ivanna-ostrovets requested changes
You have inconsistency problem with formatting your code. Please, fix this.
It might be helpful to use .editorconfig to prevent such problems.

2017-07-14 11:50 UTC, ivanna-ostrovets commented
Also check your CSS, please.

2017-07-14 12:59 UTC, ivanna-ostrovets approved these changes

2017-07-16 21:43 UTC, merged